sudo: required
language: java

jdk:
  - oraclejdk8

env:
  global:
    - CACHE_DIR=$HOME/.cache
    - MAVEN_HOME=/usr/local/maven
    - MAVEN_CFG=$HOME/.m2

cache:
  directories:
    - $CACHE_DIR
    - $MAVEN_CFG

install:
  - bash .travis/maven_cfg.sh

script:
  - mvn package -DskipTests
  - mvn package appassembler:assemble

before_deploy:
  - bash .travis/create_release.sh

deploy:
  - provider: releases
    api_key: $GITHUB_API_TOKEN
    file: utPLSQL-cli.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: bintray
    file: bintray.json
    user: $BINTRAY_USER
    key: $BINTRAY_API_KEY
    dry-run: false
    on: develop
